version: '3.7'

services:
  
  # Database - MySql
  mysql:
    image: mysql:latest
    volumes:
      - mysql_data_container:/data/db/mysql
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=alexmask
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=petstore
    restart: always

volumes:
  mysql_data_container:
